disaster_warnings = {
    "Japan": "Prone to earthquakes and tsunamis. Always follow local disaster alerts.",
    "Philippines": "Prone to volcanic eruptions, typhoons, and earthquakes. Monitor PAGASA and PHIVOLCS updates.",
    "Indonesia": "Located on the Ring of Fire – active volcanoes and frequent earthquakes.",
    "Nepal": "High risk of landslides and earthquakes in hilly and mountainous areas.",
    "India": "Cyclones on eastern and western coasts, landslides in Himalayan regions, and heatwaves in summers.",
    "United States": "Hurricane-prone in the southeast, wildfires in the west, and tornadoes in the Midwest.",
    "Mexico": "Earthquake-prone zones especially near Pacific coast; hurricanes on eastern coast.",
    "China": "Seismic risk in western regions; typhoons in southeast; flooding in major river basins.",
    "Australia": "Bushfires in summer, cyclones in the north, and flooding in various regions.",
    "Turkey": "Earthquake-prone due to tectonic plate boundaries.",
    "Chile": "Earthquake and tsunami prone due to subduction zones.",
    "Italy": "Active volcanoes (Vesuvius, Etna) and earthquake-prone in central and southern regions.",
    "Colombia": "Earthquakes in Andes region, hurricanes on Caribbean coast, landslides, floods.",
    "Russia": "Earthquakes (Far East), floods (Siberia), wildfires.",
    "Vanuatu": "Cyclones, earthquakes, volcanic eruptions; among highest per‑capita disaster risk.",
    "Solomon Islands": "Cyclones, earthquakes, tsunamis; also noted in highest‑risk island states.",
    "Tonga": "Cyclones, earthquakes, volcanic activity; consistent high risk.",
    "Canada": "Floods, wildfires, ice storms; increasing climate risks.",
    "Vietnam": "Typhoons, flash floods, coastal sea‑level rise.",
    "Myanmar": "Cyclones, floods, landslides.",
    "Meghalaya": "Prone to extremely heavy rainfall, flash floods, and landslides, especially during monsoon season.",
    "Bangladesh": "Flood-prone and affected by cyclones and river erosion."
}


location_to_country = {
    "tokyo": "Japan",
    "osaka": "Japan",
    "manila": "Philippines",
    "cebu": "Philippines",
    "jakarta": "Indonesia",
    "bali": "Indonesia",
    "los angeles": "USA",
    "san francisco": "USA",
    "miami": "USA",
    "new orleans": "USA",
    "dallas": "USA",
    "chicago": "USA",
    "santiago": "Chile",
    "valparaíso": "Chile",
    "mumbai": "India",
    "kolkata": "India",
    "chennai": "India",
    "delhi": "India",
    "guwahati": "India",
    "bengaluru": "India",
    "meghalaya": "India",
    "shimla":"India",
    "kathmandu": "Nepal",
    "rome": "Italy",
    "sicily": "Italy",
    "milan": "Italy",
    "istanbul": "Turkey",
    "ankara": "Turkey",
    "mexico city": "Mexico",
    "guadalajara": "Mexico",
    "dhaka": "Bangladesh",
    "chittagong": "Bangladesh",
    "beijing": "China",
    "chengdu": "China",
    "guangzhou": "China",
    "shanghai": "China",
    "sydney": "Australia",
    "melbourne": "Australia",
    "darwin": "Australia",
    "bogotá": "Colombia",
    "medellín": "Colombia",
    "port vila": "Vanuatu",
    "honiara": "Solomon Islands",
    "moscow": "Russia",
    "toronto": "Canada",
    "vancouver": "Canada",
    "calgary": "Canada",
    "hanoi": "Vietnam",
    "yangon": "Myanmar"
}